import type { AppLanguage } from "@/lib/language";

export const appCopy = {
  fr: {
    nav: {
      journal: "Journal",
      dashboard: "Dashboard",
      radar: "Radar",
      profile: "Profil",
    },
    appShell: {
      brand: "Lucide",
      sessionFallback: "Session",
      defaultTitle: "Lucide",
      defaultSubtitle: "Voir clair sur ses paris.",
      pages: {
        journal: {
          title: "Journal",
          subtitle: "Saisir ses mises et garder une trace nette.",
        },
        dashboard: {
          title: "Tableau de bord",
          subtitle: "Voir la realite en chiffres, sans bruit.",
        },
        radar: {
          title: "Radar",
          subtitle: "Suggestions cadres par date, sans bruit.",
        },
        profile: {
          title: "Profil",
          subtitle: "Parametres, soutien et informations personnelles.",
        },
      },
    },
    login: {
      signInTab: "Connexion",
      signUpTab: "Creer un compte",
      titleSignIn: "Connexion",
      titleSignUp: "Creer un compte",
      descriptionSignIn: "Connecte-toi avec ton email et ton mot de passe.",
      descriptionSignUp: "Inscription simple, rapide et propre. Email, mot de passe, et c'est parti.",
      emailLabel: "Email",
      emailPlaceholder: "toi@exemple.com",
      passwordLabel: "Mot de passe",
      passwordPlaceholder: "Au moins 6 caracteres",
      passwordHint: "Mot de passe libre, minimum 6 caracteres.",
      verifyEmailTitle: "Verifie ton email",
      accountReadyTitle: "Compte pret",
      envMissing: "Ajoute `VITE_SUPABASE_URL` et `VITE_SUPABASE_ANON_KEY` dans `.env` pour activer la connexion.",
      signingIn: "Connexion en cours...",
      signingUp: "Creation en cours...",
      signInCta: "Se connecter",
      signUpCta: "Creer mon compte",
      createdAccountVerify: (email: string) => `Compte cree. Verifie ton email pour activer l'acces a ${email}.`,
      createdAccountConnecting: "Compte cree. Connexion en cours...",
    },
    splash: {
      title: "Chargement",
      description: "Connexion a ton espace en cours.",
    },
    notFound: {
      title: "Page introuvable",
      description: "Cette vue n'existe pas ou n'est pas encore branchee.",
      cta: "Retour au tableau de bord",
    },
    profile: {
      noEmail: "Aucun email",
      memberSince: "Membre depuis",
      profileCreating: "Profil en cours de creation",
      usernamePlaceholder: "Pseudo",
      profileUpdated: "Profil mis a jour.",
      save: "Enregistrer",
      saving: "Sauvegarde...",
      appearanceTitle: "Apparence",
      appearanceDescription: "Choisis le theme le plus confortable.",
      active: "Actif",
      themeLightLabel: "Clair",
      themeLightDescription: "Plus net, plus lumineux.",
      themeDarkLabel: "Sombre",
      themeDarkDescription: "Plus discret, plus dense.",
      languageTitle: "Langue",
      languageDescription: "Choisis la langue de l'interface.",
      languageHint: "Le changement s'applique tout de suite sur cet appareil. Enregistre pour le rattacher au profil.",
      languageFrenchLabel: "Francais",
      languageFrenchDescription: "Interface et messages en francais.",
      languageEnglishLabel: "English",
      languageEnglishDescription: "Interface et messages en anglais.",
      currencyTitle: "Devise",
      currencyDescription: "Choisis la devise d'affichage pour tes mises et tes statistiques.",
      currencyActive: "Devise active",
      currencyHint: "Cette devise s'applique aux mises et aux stats. Les paiements Radar et soutien restent en FCFA.",
      supportTitle: "Soutenir Lucide",
      supportDescription: "Tes dons soutiennent le projet, l'hebergement et les futures ameliorations de Radar.",
      amountCustom: "Libre",
      amountPlaceholder: "Montant en FCFA",
      selectedAmount: "Montant choisi",
      chooseAmount: "Choisis un montant",
      orangeDescription: "Pour soutenir Lucide avec Orange Money.",
      mobileDescription: "Pour soutenir Lucide avec Mobile Money.",
      waveDescription: "Si tu soutiens via Wave, copie simplement ce numero.",
      donate: "Donner",
      chooseAmountCta: "Choisir un montant",
      numberCopied: "Numero copie",
      copyNumber: "Copier le numero",
      copyFailed: "Copie impossible pour le moment.",
      supportHint: "Choisis ton montant puis touche le service que tu utilises.",
      signingOut: "Sortie...",
      signOut: "Deconnexion",
      contactDeveloper: "Contacter le developpeur",
      developerMessage: "Bonjour, j'ai une question sur Lucide.",
      adminAccessClose: "Fermer l'acces admin",
      adminAccessTitle: "Acces admin Radar",
      adminAccessDescription: "Mot de passe requis pour ouvrir l'espace de generation.",
      adminPasswordPlaceholder: "Mot de passe admin",
      cancel: "Annuler",
      opening: "Ouverture...",
      open: "Ouvrir",
      adminUnavailable: "Acces admin impossible.",
      adminGeneratorClose: "Fermer le generateur admin",
      adminGeneratorTitle: "Generateur admin Radar",
      adminGeneratorDescription: "Espace cache pour preparer un code a usage unique a renvoyer manuellement au client.",
      userEmailPlaceholder: "Email utilisateur",
      customPack: "Pack personnalise",
      tokensPlaceholder: "Jetons",
      amountFcfaPlaceholder: "Montant FCFA",
      currentUnitBase: "Base actuelle",
      perToken: "par jeton",
      oneTimeUse: "Usage unique",
      codeGenerated: "Code genere. Tu peux maintenant l'envoyer manuellement au client via WhatsApp.",
      generationUnavailable: "Generation impossible.",
      closing: "Fermeture...",
      closeAccess: "Fermer l'acces",
      generating: "Generation...",
      generateCode: "Generer le code",
      codeReadyToSend: "Code pret a envoyer",
      expiresOn: "Expire le",
      codeCopied: "Code copie",
      copyCode: "Copier le code",
      adminCopyFailed: "Copie impossible pour le moment.",
      tokensUnit: "jetons",
    },
  },
  en: {
    nav: {
      journal: "Journal",
      dashboard: "Dashboard",
      radar: "Radar",
      profile: "Profile",
    },
    appShell: {
      brand: "Lucide",
      sessionFallback: "Session",
      defaultTitle: "Lucide",
      defaultSubtitle: "See clearly through your bets.",
      pages: {
        journal: {
          title: "Journal",
          subtitle: "Log your bets and keep a clean record.",
        },
        dashboard: {
          title: "Dashboard",
          subtitle: "See the truth in numbers, without noise.",
        },
        radar: {
          title: "Radar",
          subtitle: "Framed suggestions by date, without noise.",
        },
        profile: {
          title: "Profile",
          subtitle: "Settings, support, and personal information.",
        },
      },
    },
    login: {
      signInTab: "Sign in",
      signUpTab: "Create account",
      titleSignIn: "Sign in",
      titleSignUp: "Create an account",
      descriptionSignIn: "Sign in with your email and password.",
      descriptionSignUp: "Simple, fast, clean sign-up. Email, password, and you're in.",
      emailLabel: "Email",
      emailPlaceholder: "you@example.com",
      passwordLabel: "Password",
      passwordPlaceholder: "At least 6 characters",
      passwordHint: "Choose any password, minimum 6 characters.",
      verifyEmailTitle: "Check your email",
      accountReadyTitle: "Account ready",
      envMissing: "Add `VITE_SUPABASE_URL` and `VITE_SUPABASE_ANON_KEY` to `.env` to enable sign-in.",
      signingIn: "Signing in...",
      signingUp: "Creating account...",
      signInCta: "Sign in",
      signUpCta: "Create my account",
      createdAccountVerify: (email: string) => `Account created. Check your email to activate access for ${email}.`,
      createdAccountConnecting: "Account created. Signing you in...",
    },
    splash: {
      title: "Loading",
      description: "Signing you into your space.",
    },
    notFound: {
      title: "Page not found",
      description: "This view does not exist or is not wired yet.",
      cta: "Back to dashboard",
    },
    profile: {
      noEmail: "No email",
      memberSince: "Member since",
      profileCreating: "Profile is still being created",
      usernamePlaceholder: "Username",
      profileUpdated: "Profile updated.",
      save: "Save",
      saving: "Saving...",
      appearanceTitle: "Appearance",
      appearanceDescription: "Choose the most comfortable theme.",
      active: "Active",
      themeLightLabel: "Light",
      themeLightDescription: "Cleaner and brighter.",
      themeDarkLabel: "Dark",
      themeDarkDescription: "More discreet and denser.",
      languageTitle: "Language",
      languageDescription: "Choose the interface language.",
      languageHint: "The change applies immediately on this device. Save to sync it with your profile.",
      languageFrenchLabel: "French",
      languageFrenchDescription: "Interface and messages in French.",
      languageEnglishLabel: "English",
      languageEnglishDescription: "Interface and messages in English.",
      currencyTitle: "Currency",
      currencyDescription: "Choose the display currency for your bets and stats.",
      currencyActive: "Active currency",
      currencyHint: "This currency applies to bets and stats. Radar and support payments still stay in FCFA.",
      supportTitle: "Support Lucide",
      supportDescription: "Your donations support the project, hosting, and future Radar improvements.",
      amountCustom: "Custom",
      amountPlaceholder: "Amount in FCFA",
      selectedAmount: "Selected amount",
      chooseAmount: "Choose an amount",
      orangeDescription: "Support Lucide with Orange Money.",
      mobileDescription: "Support Lucide with Mobile Money.",
      waveDescription: "If you support through Wave, simply copy this number.",
      donate: "Donate",
      chooseAmountCta: "Choose an amount",
      numberCopied: "Number copied",
      copyNumber: "Copy number",
      copyFailed: "Copy is unavailable right now.",
      supportHint: "Choose an amount, then tap the service you use.",
      signingOut: "Signing out...",
      signOut: "Sign out",
      contactDeveloper: "Contact developer",
      developerMessage: "Hello, I have a question about Lucide.",
      adminAccessClose: "Close admin access",
      adminAccessTitle: "Radar admin access",
      adminAccessDescription: "Password required to open the code generation area.",
      adminPasswordPlaceholder: "Admin password",
      cancel: "Cancel",
      opening: "Opening...",
      open: "Open",
      adminUnavailable: "Admin access is unavailable.",
      adminGeneratorClose: "Close admin generator",
      adminGeneratorTitle: "Radar admin generator",
      adminGeneratorDescription: "Hidden space to prepare a one-time code to send back manually to the client.",
      userEmailPlaceholder: "User email",
      customPack: "Custom pack",
      tokensPlaceholder: "Tokens",
      amountFcfaPlaceholder: "Amount in FCFA",
      currentUnitBase: "Current base",
      perToken: "per token",
      oneTimeUse: "One-time use",
      codeGenerated: "Code generated. You can now send it manually to the client on WhatsApp.",
      generationUnavailable: "Generation is unavailable right now.",
      closing: "Closing...",
      closeAccess: "Close access",
      generating: "Generating...",
      generateCode: "Generate code",
      codeReadyToSend: "Code ready to send",
      expiresOn: "Expires on",
      codeCopied: "Code copied",
      copyCode: "Copy code",
      adminCopyFailed: "Copy is unavailable right now.",
      tokensUnit: "tokens",
    },
  },
} as const;

export function getCopy(language: AppLanguage) {
  return appCopy[language];
}
